# Generated by Django 5.2.4 on 2025-07-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_media_file_alter_media_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.URLField(),
        ),
    ]
