# Generated by Django 5.2.4 on 2025-08-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_category_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scheduled_publish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
